server:
  port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Mcqueen_9599
        url: jdbc:mysql://127.0.0.1:3306/inventory
        username: root
    jpa:
        show-sql: true  
        hibernate:
            ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: false
    default-model-expand-depth: -1

logging:
  level:
      '[org.springframework.security]': DEBUG

jwt:
  secretKey: secrets8o7gvk7icretsecret1
  tokenPrefix: "Bearer "
